### ISSUE TITLE
Retrieving the connected team?

### ISSUE THREAD

**Issue by excid3** [digitalocean/omniauth-digitalocean#22]
When I use OAuth to connect DigitalOcean, it asks which team I would like to connect.

Is there any way to get the name of the team that was OAuth'd? I can't find anything in the API for this.

**Comment by andrewsomething** [comment]
Hi @excid3,

This is a good call out. The OAuth response is currently lacking this information. We could add it to the info object in the token response payload. Would that work for you? 

If you'd like to jump on a call sometime to discuss, feel free to email me at asb at digitalocean.com Would love to better understand how HatchBox integrates with DO to make sure we're meeting you needs.

**Comment by excid3** [comment]
That would be great. The main thing we'd like to do is have separate API keys for a user so they can choose the team they're creating droplets on. Right now there's no way for us to tell them which is which.

Just sent you an email!

**Comment by andrewsomething** [comment]
I'm going to go ahead and close this out. The OAuth response has been updated to include team information:

https://docs.digitalocean.com/release-notes/api/#2022-03-17

And I've documented how we expose that to OmniAuth:

https://github.com/digitalocean/omniauth-digitalocean#auth-hash-schema
